USE [OnlineGym];
IF NOT EXISTS (
	SELECT *
	FROM INFORMATION_SCHEMA.TABLES
	WHERE
		TABLE_NAME = N'Athlete'
)
BEGIN
	CREATE TABLE [OnlineGym].[dbo].[Athlete]
	(
		[AthleteId] [BIGINT] IDENTITY(1, 1) NOT NULL,
		[Name] [NVARCHAR](50) NOT NULL,
		[Email] [NVARCHAR](150) NOT NULL,
		[Status] [INT] NOT NULL,
		[StatusExpirationDate] [DATETIME] NULL,
		[MoneySpent] [DECIMAL](18, 2) NOT NULL,
		CONSTRAINT [PK_Athlete] PRIMARY KEY CLUSTERED ([AthleteId] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY];
END;
